### ISSUE TITLE
benefits of this over `git clone --bare` and `git push --mirror`?

### ISSUE THREAD

**Issue by jcbhmr** [yesolutions/mirror-action#37]
Hello! 👋

I'm interested in hosting some internal Git mirrors on GitHub for some SourceForge Git repositories. I was hunting around on the GitHub Actions marketplace and found this GitHub Action. I also Googled some and found that [the "recommended" way to mirror a Git repository by GitHub](https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository) is this:

```sh
git clone --bare https://git.code.sf.net/p/mingw/regex .
git push --mirror https://github.com/octocat/mingw-regex.git
```

where `https://github.com/octocat/mingw-regex.git` can have a `https://username:password@github.com/...` auth URL part where `username` is _anything_ (even just `x`) and `password` is a GitHub Personal Access Token. https://stackoverflow.com/questions/18935539/authenticate-with-github-using-a-token

Is there an advantage to using this GitHub Action over something like this? Am I missing something?

```yml
# octocat/.github or another third repository
# .github/workflows/mirror-mingw-regex-to-octocat-mingw-regex.yml
name: Mirror mingw/regex to octocat/mingw-regex
on:
  schedule:
    - cron: "36 */6 * * *"
  workflow_dispatch:
jobs:
  mirror-mingw-regex-to-octocat-mingw-regex:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare https://git.code.sf.net/p/mingw/regex .
      - run: git push --mirror "https://x:$TOKEN@github.com/octocat/mingw-regex.git"
        env:
          TOKEN: ${{ secrets.MINGW_REGEX_TOKEN }}
```
